//! Save/load: `level.ron` (the world header) and the save directory as a
//! whole (`docs/PHASE1_ARCHITECTURE.md` §7, issue #60).
//!
//! ```text
//! saves/<world>/
//!   level.ron                      # seed, tick, RNG, player, block id table
//!   region/r.<rx>.<ry>.<rz>.cbr    # 32×32×32 chunks = 512³ blocks
//! ```
//!
//! Lives here, in `cubara-sim`, not in `cubara-world` -- the header carries
//! tick/RNG/player state, and `cubara-world` must never know about the
//! player (§1's crate table). `cubara_world::region` owns the chunk data
//! half; this module owns the header and ties the two together. Same
//! reasoning [`crate::WorldHash`] (block 1.8) already established for why
//! this crate, not that one.

use crate::inventory::Inventory;
use std::collections::HashMap;
use std::path::Path;

use cubara_voxel::{BlockId, BlockRegistry, ChunkCoord};
use cubara_world::{region, TerrainBlocks, World, WORLDGEN_VERSION};
use serde::{Deserialize, Serialize};

use crate::player::Player;
use crate::rng::WorldRng;
use crate::Sim;

/// `level.ron`'s own schema version -- independent of
/// [`cubara_world::region::REGION_FORMAT_VERSION`] and of
/// [`cubara_world::WORLDGEN_VERSION`]; each names a different thing that
/// can change on its own schedule.
pub const FORMAT_VERSION: u16 = 1;

#[derive(Debug, Clone, Serialize, Deserialize)]
struct SavedRng {
    state: u64,
    inc: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct SavedPlayer {
    pos: (f32, f32, f32),
    vel: (f32, f32, f32),
    yaw: f32,
    pitch: f32,
    on_ground: bool,
    free_fly: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct SavedHeader {
    format_version: u16,
    worldgen_version: u32,
    seed: u64,
    tick: u64,
    rng: SavedRng,
    player: SavedPlayer,
    /// The id → name table in force when this world was saved (§3.4, §7.2).
    /// Loading resolves each name against the *current* registry, so ids
    /// may be reassigned freely between runs.
    blocks: Vec<(u16, String)>,
}

/// A save failed. Every variant names the problem.
#[derive(Debug)]
pub enum SaveError {
    Io(std::io::Error),
    Ron(ron::Error),
    Region(region::RegionError),
}

impl std::fmt::Display for SaveError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SaveError::Io(e) => write!(f, "save I/O error: {e}"),
            SaveError::Ron(e) => write!(f, "failed to write level.ron: {e}"),
            SaveError::Region(e) => write!(f, "failed to write region files: {e}"),
        }
    }
}

impl std::error::Error for SaveError {}

/// A load failed. Every variant names the problem -- in particular the two
/// hard errors §7.2 requires: [`LoadError::UnknownBlockName`] (a name the
/// current registry doesn't know -- a removed mod) and
/// [`LoadError::WorldgenVersionMismatch`] (the generator that made this
/// world isn't the one running now, so its unedited chunks would
/// regenerate into a different shape around the player's edits, §7.4).
#[derive(Debug)]
pub enum LoadError {
    Io(std::io::Error),
    Ron(ron::de::SpannedError),
    Region(region::RegionError),
    /// This build's `level.ron` reader doesn't know this schema version.
    UnsupportedFormatVersion(u16),
    /// A block name the header's id table lists that the current registry
    /// doesn't have.
    UnknownBlockName(String),
    /// The generator that produced this world doesn't match the one
    /// running now.
    WorldgenVersionMismatch {
        expected: u32,
        found: u32,
    },
    /// A region file references a saved id the header's own table never
    /// listed -- a corrupt or hand-edited save, not a normal mismatch (that
    /// case is [`UnknownBlockName`], caught earlier, at the header).
    UnmappedChunkIds {
        chunk: ChunkCoord,
    },
}

impl std::fmt::Display for LoadError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LoadError::Io(e) => write!(f, "load I/O error: {e}"),
            LoadError::Ron(e) => write!(f, "failed to parse level.ron: {e}"),
            LoadError::Region(e) => write!(f, "failed to read region files: {e}"),
            LoadError::UnsupportedFormatVersion(v) => write!(
                f,
                "level.ron format version {v} is not supported (expected {FORMAT_VERSION})"
            ),
            LoadError::UnknownBlockName(name) => write!(
                f,
                "save references block \"{name}\", which the current registry does not define \
                 (a removed mod?)"
            ),
            LoadError::WorldgenVersionMismatch { expected, found } => write!(
                f,
                "save was generated by worldgen version {found}, but this build is version \
                 {expected} -- refusing to load, since unedited chunks would regenerate \
                 differently around the player's edits"
            ),
            LoadError::UnmappedChunkIds { chunk } => write!(
                f,
                "chunk {chunk:?} references a block id not listed in level.ron's own id table \
                 (corrupt or hand-edited save)"
            ),
        }
    }
}

impl std::error::Error for LoadError {}

/// Save `sim`/`world` to `dir` (created if it doesn't exist): `level.ron`
/// plus one region file per dirty region under `dir/region/`. `registry`
/// supplies the id → name table (§7.2); `blocks` is what
/// [`cubara_world::World::edited_chunk_at`] resolves grass/soil/stone
/// against, same as everywhere else that materializes a chunk.
pub fn save_world(
    dir: &Path,
    sim: &Sim,
    world: &World,
    registry: &BlockRegistry,
    blocks: TerrainBlocks,
) -> Result<(), SaveError> {
    std::fs::create_dir_all(dir).map_err(SaveError::Io)?;

    let blocks_table: Vec<(u16, String)> = registry
        .ids()
        .filter_map(|id| registry.name_of(id).map(|name| (id.0, name.to_string())))
        .collect();

    let header = SavedHeader {
        format_version: FORMAT_VERSION,
        worldgen_version: WORLDGEN_VERSION,
        seed: world.seed(),
        tick: sim.tick,
        rng: SavedRng {
            state: sim.rng.state,
            inc: sim.rng.inc,
        },
        player: SavedPlayer {
            pos: sim.player.pos.into(),
            vel: sim.player.velocity.into(),
            yaw: sim.player.yaw,
            pitch: sim.player.pitch,
            on_ground: sim.player.on_ground,
            free_fly: sim.player.free_fly,
        },
        blocks: blocks_table,
    };

    let text = ron::ser::to_string_pretty(&header, ron::ser::PrettyConfig::default())
        .map_err(SaveError::Ron)?;
    std::fs::write(dir.join("level.ron"), text).map_err(SaveError::Io)?;

    region::save_regions(&dir.join("region"), world, blocks).map_err(SaveError::Region)?;
    Ok(())
}

/// Load a world saved by [`save_world`]. Regenerates every chunk
/// [`cubara_world::World::dirty_chunks`] didn't cover (§7.4's whole point);
/// `registry`/`blocks` play the same role as in `save_world`, resolved
/// against *this* run's registry, which need not assign the same ids the
/// save was made with -- that's exactly what the header's id table exists
/// to bridge (§7.2).
pub fn load_world(
    dir: &Path,
    registry: &BlockRegistry,
    blocks: TerrainBlocks,
) -> Result<(Sim, World), LoadError> {
    let text = std::fs::read_to_string(dir.join("level.ron")).map_err(LoadError::Io)?;
    let header: SavedHeader = ron::from_str(&text).map_err(LoadError::Ron)?;

    if header.format_version != FORMAT_VERSION {
        return Err(LoadError::UnsupportedFormatVersion(header.format_version));
    }
    if header.worldgen_version != WORLDGEN_VERSION {
        return Err(LoadError::WorldgenVersionMismatch {
            expected: WORLDGEN_VERSION,
            found: header.worldgen_version,
        });
    }

    let mut remap: HashMap<u16, BlockId> = HashMap::with_capacity(header.blocks.len());
    for (saved_id, name) in &header.blocks {
        let runtime_id = registry
            .id_of(name)
            .ok_or_else(|| LoadError::UnknownBlockName(name.clone()))?;
        remap.insert(*saved_id, runtime_id);
    }

    let mut world = World::with_seed(header.seed);

    let region_dir = dir.join("region");
    if region_dir.is_dir() {
        for entry in std::fs::read_dir(&region_dir).map_err(LoadError::Io)? {
            let entry = entry.map_err(LoadError::Io)?;
            let Some(name) = entry.file_name().to_str().map(str::to_string) else {
                continue;
            };
            let Some(region_coord) = region::parse_region_file_name(&name) else {
                continue;
            };
            let chunks =
                region::read_region_file(&entry.path(), region_coord).map_err(LoadError::Region)?;
            for (coord, chunk) in chunks {
                let remapped = chunk
                    .remap_ids(|id| remap.get(&id.0).copied())
                    .ok_or(LoadError::UnmappedChunkIds { chunk: coord })?;
                world.load_chunk_edits(coord, &remapped, blocks);
            }
        }
    }

    let player = Player {
        pos: glam::Vec3::new(
            header.player.pos.0,
            header.player.pos.1,
            header.player.pos.2,
        ),
        velocity: glam::Vec3::new(
            header.player.vel.0,
            header.player.vel.1,
            header.player.vel.2,
        ),
        on_ground: header.player.on_ground,
        free_fly: header.player.free_fly,
        yaw: header.player.yaw,
        pitch: header.player.pitch,
        // Not in the format yet -- the save extension is block 2.8, which adds
        // the item id table this needs (PHASE2_ARCHITECTURE.md §8). A loaded
        // world starts empty-handed until then, deliberately and visibly,
        // rather than silently half-restoring an inventory.
        inventory: Inventory::new(),
    };

    let sim = Sim {
        tick: header.tick,
        rng: WorldRng {
            state: header.rng.state,
            inc: header.rng.inc,
        },
        player,
        target: None, // recomputed by the first tick; not part of saved state
    };

    Ok((sim, world))
}
